# Form implementation generated from reading ui file 'service_mode.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(540, 840)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 521, 771))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.command_line = QtWidgets.QLineEdit(parent=self.widget)
        self.command_line.setText("")
        self.command_line.setObjectName("command_line")
        self.horizontalLayout.addWidget(self.command_line)
        self.btn_send_comand = QtWidgets.QPushButton(parent=self.widget)
        self.btn_send_comand.setObjectName("btn_send_comand")
        self.horizontalLayout.addWidget(self.btn_send_comand)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.console = QtWidgets.QTextBrowser(parent=self.widget)
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)
        self.btn_beck = QtWidgets.QPushButton(parent=self.widget)
        self.btn_beck.setObjectName("btn_beck")
        self.verticalLayout.addWidget(self.btn_beck)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_send_comand.setText(_translate("MainWindow", "Отправить"))
        self.btn_beck.setText(_translate("MainWindow", "Возврат"))